//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelegramBot.Application.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BotMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BotMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("TelegramBot.Application.Resources.BotMessages", typeof(BotMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string HelpCommand {
            get {
                return ResourceManager.GetString("HelpCommand", resourceCulture);
            }
        }
        
        internal static string UnknownCommand {
            get {
                return ResourceManager.GetString("UnknownCommand", resourceCulture);
            }
        }
        
        internal static string NoDataAvailable {
            get {
                return ResourceManager.GetString("NoDataAvailable", resourceCulture);
            }
        }
        
        internal static string DonateCommand {
            get {
                return ResourceManager.GetString("DonateCommand", resourceCulture);
            }
        }
        
        internal static string DonationInvoiceDescription {
            get {
                return ResourceManager.GetString("DonationInvoiceDescription", resourceCulture);
            }
        }
        
        internal static string CannotCreateInvoiceError {
            get {
                return ResourceManager.GetString("CannotCreateInvoiceError", resourceCulture);
            }
        }
        
        internal static string Donation {
            get {
                return ResourceManager.GetString("Donation", resourceCulture);
            }
        }
        
        internal static string DonationDescription {
            get {
                return ResourceManager.GetString("DonationDescription", resourceCulture);
            }
        }
        
        internal static string ThanksForSupportMessage {
            get {
                return ResourceManager.GetString("ThanksForSupportMessage", resourceCulture);
            }
        }
        
        internal static string SuccessfulRefundMessage {
            get {
                return ResourceManager.GetString("SuccessfulRefundMessage", resourceCulture);
            }
        }
        
        internal static string SetUserLanguageCommand {
            get {
                return ResourceManager.GetString("SetUserLanguageCommand", resourceCulture);
            }
        }
        
        internal static string UserLanguageWasSetIntoRussian {
            get {
                return ResourceManager.GetString("UserLanguageWasSetIntoRussian", resourceCulture);
            }
        }
        
        internal static string UserLanguageWasSetIntoEnglish {
            get {
                return ResourceManager.GetString("UserLanguageWasSetIntoEnglish", resourceCulture);
            }
        }
        
        internal static string UserLanguageWasSetIntoAuto {
            get {
                return ResourceManager.GetString("UserLanguageWasSetIntoAuto", resourceCulture);
            }
        }
        
        internal static string HelpCommandDescription {
            get {
                return ResourceManager.GetString("HelpCommandDescription", resourceCulture);
            }
        }
        
        internal static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        internal static string CommandNotAllowedInGroups {
            get {
                return ResourceManager.GetString("CommandNotAllowedInGroups", resourceCulture);
            }
        }
        
        internal static string BotStatistics {
            get {
                return ResourceManager.GetString("BotStatistics", resourceCulture);
            }
        }
        
        internal static string CurrentWeatherMessage {
            get {
                return ResourceManager.GetString("CurrentWeatherMessage", resourceCulture);
            }
        }
        
        internal static string WeatherCommand {
            get {
                return ResourceManager.GetString("WeatherCommand", resourceCulture);
            }
        }
        
        internal static string NewYorkCity {
            get {
                return ResourceManager.GetString("NewYorkCity", resourceCulture);
            }
        }
        
        internal static string ParisCity {
            get {
                return ResourceManager.GetString("ParisCity", resourceCulture);
            }
        }
        
        internal static string WeatherCommandDescription {
            get {
                return ResourceManager.GetString("WeatherCommandDescription", resourceCulture);
            }
        }
    }
}
